### PR TITLE
Several enhancements for file information in dialog and add functionality to filter file versions by user

### PR DESCRIPTION
**Pull request by tmaestrini**

### CODE REVIEW

**Comment by Tanddant** [comment]
@tmaestrini - I just skimmed over the changes (not at a PC yet, so just in the app) - one concern I have, when you filter by Author, will it show all the changes in-between two "updates" as having been done by that author?

Maybe we should apply the author filter client side, after fetching and parsing the data, or maybe I'm missing the obvious piece since I'm not actually running the code ATM 😊

**Comment by tmaestrini** [comment]
As I understand: yes, it does! 
But you're right - we could do the filtering part by author on the client side (and notnin the provider itself). This reduces the payload over the network. Will check out later (or feel free to improve!) 😀

**Comment by tmaestrini** [comment]
@Tanddant I've changed the author filtering to client side – as discussed in previous thread. Are you now fine with this solution? 😄

**Comment by Tanddant** [comment]
I'm fine with anything, as long as you're happy with it 😊

My git skill apparently aren't great enough to checkout a PR, so I'll trust you that it works, and we'll merge 😂

**Comment by tmaestrini** [comment]
> My git skill apparently aren't great enough to checkout a PR, so I'll trust you that it works, and we'll merge 😂

Of course it works... 😂😂😂

**Pull request merged**
